apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres-system
  labels:
    app: postgres
spec:
  selector:
   app: postgres
  type: LoadBalancer
  ports:
    - name: postgres-port
      protocol: TCP
      port: 5432
      targetPort: 5432
  loadBalancerIP: 192.168.0.205
